#!/bin/bash
# https://fpm.readthedocs.io/en/latest/cli-reference.html
# Value 1: program-name
# Value 2: architecture -> valid values are: x86_64/amd64, aarch64, native (current architecture), all/noarch/any

PROGRAM_NAME=helloapp
ARCH=amd64
#ARCH=${uname -m}
#ARCH=${dpkg --print-architecture}

# Debian/Ubuntu
fpm --force \
  --log info \
  --architecture ${ARCH} \
  --input-type dir \
  --output-type deb \
  --package ${PROGRAM_NAME}-latest-${ARCH}.deb \
  --name ${PROGRAM_NAME} \
  --version 0.1.0 \
  --license MIT \
  --description "${PROGRAM_NAME}" \
  --maintainer "The Maintainer" \
  --url "https://www.the_maintainer.de/" \
  --deb-systemd ${PROGRAM_NAME}.service \
  --deb-systemd-enable \
  --deb-systemd-auto-start \
  --after-remove post-remove.sh \
  --before-install pre-install.sh \
  ${PROGRAM_NAME}=/usr/bin/${PROGRAM_NAME} \
  config.json=/etc/${PROGRAM_NAME}/config.json

# Fedora/RedHat/openSUSE
fpm --force \
  --log info \
  --architecture ${ARCH} \
  --input-type dir \
  --output-type rpm \
  --package ${PROGRAM_NAME}-latest-${ARCH}.rpm \
  --name ${PROGRAM_NAME} \
  --version 0.1.0 \
  --license MIT \
  --description "${PROGRAM_NAME}" \
  --maintainer "The Maintainer" \
  --url "https://www.the_maintainer.de/" \
  --after-remove post-remove.sh \
  --before-install pre-install.sh \
  ${PROGRAM_NAME}=/usr/bin/${PROGRAM_NAME} \
  config.json=/etc/${PROGRAM_NAME}/config.json \
  ${PROGRAM_NAME}.service=/etc/systemd/system/${PROGRAM_NAME}.service

# Installation using the console on:
# - Debian: sudo apt install ./helloapp-latest-amd64.deb
# - Ubuntu: sudo apt install ./helloapp-latest-amd64.deb
# - Fedora: sudo dnf install ./helloapp-latest-amd64.rpm
# - RedHat: sudo yum install ./helloapp-latest-amd64.rpm
# - openSUSE: sudo zypper install ./helloapp-latest-amd64.rpm
